### ISSUE TITLE
1. Linux Academy Slack - https://linuxacademy-community-slack.herokuapp.com/ none-working link

### ISSUE THREAD

**Issue by KevinArellano94** [AWS-Discord/AWS-FAQ#38]
Most likely the Heroku project stopped working once it became a paid-feature.

**Comment by KevinArellano94** [comment]
Feel free to let me know if you want me to deploy it to Netlify.

**Comment by KevinArellano94** [comment]
Location: https://github.com/AWS-Discord/AWS-FAQ/blob/master/general.md

**Comment by Jurgis325** [comment]
Link removed
